import Head from "next/head";

import MovieDetailsContainer from "@/containers/details";

export default function Home() {
  return (
    <>
      <Head>
        <title>Movie Details</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MovieDetailsContainer />
    </>
  );
}
